const NUMBER_OF_TABLES = 16;
const ADD_TABLE_ITEM = "ADD_TABLE_ITEM";
const DELETE_TABLE_ITEM = "DELETE_TABLE_ITEM";
const SELECT_TABLE = "SELECT_TABLE";
const TOGGLE_TABLE = "TOGGLE_TABLE";
const INCREMENT_EARNINGS = "INCREMENT_EARNINGS";

module.exports = {
  NUMBER_OF_TABLES,
  ADD_TABLE_ITEM,
  DELETE_TABLE_ITEM,
  SELECT_TABLE,
  TOGGLE_TABLE,
  INCREMENT_EARNINGS,
}
